// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using qrmenusistemiuygulama18.Data;

#nullable disable

namespace qrmenusistemiuygulama18.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413071632_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("qrmenusistemiuygulama18.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("qrmenusistemiuygulama18.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("qrmenusistemiuygulama18.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("qrmenusistemiuygulama18.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("qrmenusistemiuygulama18.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TableNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            TableNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            TableNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            TableNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            TableNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            TableNumber = 6
                        },
                        new
                        {
                            Id = 7,
                            TableNumber = 7
                        },
                        new
                        {
                            Id = 8,
                            TableNumber = 8
                        },
                        new
                        {
                            Id = 9,
                            TableNumber = 9
                        },
                        new
                        {
                            Id = 10,
                            TableNumber = 10
                        },
                        new
                        {
                            Id = 11,
                            TableNumber = 11
                        },
                        new
                        {
                            Id = 12,
                            TableNumber = 12
                        },
                        new
                        {
                            Id = 13,
                            TableNumber = 13
                        },
                        new
                        {
                            Id = 14,
                            TableNumber = 14
                        },
                        new
                        {
                            Id = 15,
                            TableNumber = 15
                        },
                        new
                        {
                            Id = 16,
                            TableNumber = 16
                        },
                        new
                        {
                            Id = 17,
                            TableNumber = 17
                        },
                        new
                        {
                            Id = 18,
                            TableNumber = 18
                        },
                        new
                        {
                            Id = 19,
                            TableNumber = 19
                        },
                        new
                        {
                            Id = 20,
                            TableNumber = 20
                        });
                });

            modelBuilder.Entity("qrmenusistemiuygulama18.Models.Order", b =>
                {
                    b.HasOne("qrmenusistemiuygulama18.Models.Table", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("qrmenusistemiuygulama18.Models.OrderItem", b =>
                {
                    b.HasOne("qrmenusistemiuygulama18.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("qrmenusistemiuygulama18.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("qrmenusistemiuygulama18.Models.Product", b =>
                {
                    b.HasOne("qrmenusistemiuygulama18.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("qrmenusistemiuygulama18.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("qrmenusistemiuygulama18.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("qrmenusistemiuygulama18.Models.Table", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
